apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.tmax.io
  annotations:
    operator.version: 4.1.0.15
spec:
  group: tmax.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: registries
    singular: registry
    kind: Registry
    shortNames:
    - reg
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [spec]
      properties:
        operatorStartTime:
          type: string
        spec:
          type: object
          required: [image, loginId, loginPassword, service, persistentVolumeClaim]
          description: registry information
          properties:
            image:
              type: string
            description:
              type: string
            loginId:
              type: string
            loginPassword:
              type: string
            customConfigYml:
              type: string
              description: "The name of the configmap where the registry config.yml content"
            service:
              type: object
              required: [type]
              properties:
                port:
                  type: integer
                  description: "external port (default: 443)"
                nodeIP:
                  type: string
                  description: "if service type is NodePort, set NodeIP to assign to the registry"
                nodePort:
                  type: integer
                  description: "if service type is NodePort, you can set 30000~32767"
                type:
                  type: string
                  enum: [ClusterIP, NodePort, LoadBalancer]
            persistentVolumeClaim:
              type: object
              required: [accessModes, storageSize, storageClassName]
              properties:
                accessModes:
                  type: array
                  items:
                    type: string
                    enum: [ReadWriteOnce, ReadWriteMany]
                storageSize:
                  type: string
                  description: "enter the desired storage size (ex: 10Gi)"
                storageClassName:
                  type: string
                  description: "enter storage class name available (ex: csi-cephfs-sc)"
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                required: [type]
                properties:
                  lastTrasnsitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
            phase:
              type: string
            message:
              type: string
            reason:
              type: string
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Image
    type: string
    description: Registry Image
    JSONPath: .spec.image
  - name: Capacity
    type: string
    description: Registry PVC Size
    JSONPath: .spec.persistentVolumeClaim.storageSize
  - name: Status
    type: string
    description: Registry Status
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp

