apiVersion: tmax.io/v1
kind: Registry
metadata: 
  name: tmax-registry
  namespace: hypercloud-system
  labels:
    obj: registry
spec:
  image: 192.168.6.110:5000/registry:b004
  description: test
  loginId: tmax
  loginPassword: tmax123
  service:
     type: LoadBalancer
  persistentVolumeClaim:
     accessModes: [ReadWriteMany]
     storageSize: 10Gi
     storageClassName: csi-cephfs-sc
