apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: usersecuritypolicies.tmax.io
  annotations:
    operator.version: 4.1.0.23
spec:
  group: tmax.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: usersecuritypolicies
    singular: usersecuritypolicy
    kind: Usersecuritypolicy
    shortNames:
    - usp
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:     
        type: object
        required: [otpEnable, otp]
        description: User Security Policy for OTP info
        properties:
          otpEnable:
            description: t/f
            type: string
          otp:
            type: string
            description: OTP Number 
          ipRange:
            type: string
            description: ip range for otp enable user    