apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceclaims.tmax.io
spec:
  group: tmax.io
  scope: Cluster
  names:
    plural: namespaceclaims
    singular: namespaceclaim
    kind: NamespaceClaim
    shortNames:
    - nsc
  preserveUnknownFields: true
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
        
        # Users use namespaceclaim to request namespace and quotas.
        # The spec of namespaceclaim is the same as resourcequota.
        # Admins can change the 'status' of the namespaceclaim.
        # If Admin change the Status to 'Success', a namespace and resourcequota are created.
        type: object
        required: [resourceName,apiVersion,kind,metadata,spec]
        properties:
          resourceName:
            type: string
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
          spec:
            # Equal Resource Quota Spec
            type: object
            properties:
              hard:
                type: object
                properties:
                  limits.cpu:
                    x-kubernetes-int-or-string: true
                    type: number
                  limits.memory:
                    x-kubernetes-int-or-string: true
                  requests.cpu:
                    x-kubernetes-int-or-string: true
                    type: number
                  requests.memory:
                    x-kubernetes-int-or-string: true
                  requests.nvidia.com/gpu:
                    x-kubernetes-int-or-string: true
                    type: number
                  requests.storage:
                    x-kubernetes-int-or-string: true
                  persistentvolumeclaims:
                    type: integer
                  <storage-class-name>.storageclass.storage.k8s.io/requests.storage:
                    x-kubernetes-int-or-string: true
                  <storage-class-name>.storageclass.storage.k8s.io/persistentvolumeclaims:
                    type: integer
                  requests.ephemeral-storage:
                    x-kubernetes-int-or-string: true
                  limits.ephemeral-storage:
                    x-kubernetes-int-or-string: true
                  count/persistentvolumeclaims:
                    type: integer
                  count/services:
                    type: integer
                  count/secrets:
                    type: integer
                  count/configmaps:
                    type: integer
                  count/replicationcontrollers:
                    type: integer
                  count/deployments.apps:
                    type: integer
                  count/replicasets.apps:
                    type: integer
                  count/statefulsets.apps:
                    type: integer
                  count/jobs.batch:
                    type: integer
                  count/cronjobs.batch:
                    type: integer
                  count/deployments.extensions:
                    type: integer
                  configmaps:
                    type: integer
                  pods:
                    type: integer
                  replicationcontrollers:
                    type: integer
                  resourcequotas:
                    type: integer
                  services:
                    type: integer
                  services.loadbalancers:
                    type: integer
                  services.nodeports:
                    type: integer
                  secrets:
                    type: integer
          status:
            type: object
            properties:
              lastTransitionTime:
                format: date-time
                type: string
              message:
                type: string
              reason:
                type: string
              status:
                type: string
                enum:
                  - Awaiting
                  - Success
                  - Reject
                  - Error
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.status
  - name: Reason
    type: string
    JSONPath: .status.reason
  subresources:
    status: {}